import { del, get, post, put } from '@/utils/request'

export const adminLogin = (username: string, password: string) =>
  post<{ token: string; adminId: number; username: string; nickname: string; roles: string[]; permissions: string[]; isSuperAdmin: number }>('/admin/login', { username, password })

export const menuTree = (adminId: number) => get<any[]>(`/menu/tree/${adminId}`)

export const orderReport = (params?: Record<string, string>) => get<Record<string, number>>('/order/admin/report', params)
export const adminOrders = (params: Record<string, unknown>) => get<any>('/order/admin/list', params)
export const getOrder = (id: number | string) => get<any>(`/order/${id}`)
export const cancelOrder = (id: number | string) => put(`/order/${id}/cancel`)
export const remarkOrder = (orderId: number | string, sellerRemark: string) => put('/order/admin/remark', { orderId, sellerRemark })
export const shipOrder = (orderId: number | string, companyCode: string) => post<string>('/order/admin/ship', { orderId, companyCode })
export const adminRefunds = (status?: number) => get<any[]>('/order/admin/refunds', { status })
export const auditRefund = (payload: Record<string, unknown>) => put('/order/refund/audit', payload)
export const paymentList = (status?: number) => get<any[]>('/payment/admin/list', { status })
export const adminSkus = () => get<any[]>('/product/admin/skus')
export const updateSkuStock = (id: number | string, stock: number) => put(`/product/sku/${id}/stock/${stock}`)
export const deleteProduct = (id: number | string) => del(`/product/${id}`)
export const shopList = () => get<any[]>('/admin/merchant/shops')

export const uploadImage = (file: File) => {
  const data = new FormData()
  data.append('file', file)
  return post<{ url: string; filename: string }>('/upload', data)
}

export const productList = (params: Record<string, unknown>) => get<any>('/product/list', params)
export const getProduct = (id: number | string) => get<any>(`/product/${id}`)
export const saveProduct = (payload: Record<string, unknown>) => post<number>('/product', payload)
export const updateProductStatus = (id: number, status: number) => put(`/product/${id}/status/${status}`)
export const categoryTree = () => get<any[]>('/product/categories')
export const saveCategory = (payload: Record<string, unknown>) => post<number>('/product/category', payload)
export const deleteCategory = (id: number) => del(`/product/category/${id}`)
export const brandList = () => get<any[]>('/product/brand/list')
export const saveBrand = (payload: Record<string, unknown>) => post<number>('/product/brand', payload)
export const deleteBrand = (id: number) => del(`/product/brand/${id}`)

export const merchantList = (params: Record<string, unknown>) => get<any>('/admin/merchant/list', params)
export const auditMerchant = (payload: Record<string, unknown>) => put('/admin/merchant/audit', payload)
export const updateMerchantStatus = (id: number | string, status: number) => put(`/admin/merchant/${id}/status/${status}`)

export const buyerList = (params: Record<string, unknown>) => get<any>('/user/admin/list', params)
export const updateBuyerStatus = (userId: number, status: number) => put(`/user/admin/${userId}/status`, null, { params: { status } })

export const bannerAdminList = () => get<any[]>('/banner/admin/list')
export const saveBanner = (payload: Record<string, unknown>) => post<number>('/banner/admin', payload)
export const deleteBanner = (id: number) => del(`/banner/admin/${id}`)
export const noticeAdminList = () => get<any[]>('/notice/admin/list')
export const saveNotice = (payload: Record<string, unknown>) => post<number>('/notice/admin', payload)
export const publishNotice = (id: number, status: number) => put(`/notice/admin/${id}/publish`, null, { params: { status } })
export const deleteNotice = (id: number) => del(`/notice/admin/${id}`)

export const commentAdminList = (auditStatus?: number) => get<any[]>('/comment/admin/list', { auditStatus })
export const replyComment = (id: number, replyContent: string) => put(`/comment/admin/${id}/reply`, null, { params: { replyContent } })
export const auditComment = (id: number, auditStatus: number) => put(`/comment/admin/${id}/audit`, null, { params: { auditStatus } })

export const companyAdminList = () => get<any[]>('/logistics/company/admin/list')
export const saveCompany = (payload: Record<string, unknown>) => post<number>('/logistics/company', payload)
export const deleteCompany = (id: number) => del(`/logistics/company/${id}`)

export const promoSeckill = () => get<any[]>('/promotion/admin/seckill')
export const saveSeckill = (payload: Record<string, unknown>) => post('/promotion/admin/seckill', payload)
export const seckillStatus = (id: number, status: number) => put(`/promotion/admin/seckill/${id}/status/${status}`)
export const promoCoupon = () => get<any[]>('/promotion/admin/coupon')
export const saveCoupon = (payload: Record<string, unknown>) => post('/promotion/admin/coupon', payload)
export const couponStatus = (id: number, status: number) => put(`/promotion/admin/coupon/${id}/status/${status}`)
export const promoDiscount = () => get<any[]>('/promotion/admin/full-discount')
export const saveDiscount = (payload: Record<string, unknown>) => post('/promotion/admin/full-discount', payload)
export const discountStatus = (id: number, status: number) => put(`/promotion/admin/full-discount/${id}/status/${status}`)
export const promoGroup = () => get<any[]>('/promotion/admin/group')
export const saveGroup = (payload: Record<string, unknown>) => post('/promotion/admin/group', payload)
export const groupStatus = (id: number, status: number) => put(`/promotion/admin/group/${id}/status/${status}`)

export const adminList = (params: Record<string, unknown>) => get<any>('/admin/list', params)
export const saveAdmin = (payload: Record<string, unknown>) => post<number>('/admin', payload)
export const deleteAdmin = (id: number) => del(`/admin/${id}`)
export const roleList = () => get<any[]>('/role/list')
export const saveRole = (payload: Record<string, unknown>) => post('/role', payload)
export const deleteRole = (id: number) => del(`/role/${id}`)
export const assignRoles = (adminId: number | string, roleIds: Array<number | string>) => post('/role/assign', { adminId, roleIds })
export const adminRoles = (adminId: number | string) => get<any[]>(`/role/admin/${adminId}`)
export const roleMenus = (roleId: number) => get<number[]>(`/role/${roleId}/menus`)
export const assignMenus = (roleId: number, menuIds: number[]) => post('/role/assign-menus', { roleId, menuIds })
export const menuList = () => get<any[]>('/menu/list')
export const saveMenu = (payload: Record<string, unknown>) => post('/menu', payload)
export const deleteMenu = (id: number) => del(`/menu/${id}`)
export const dictTypes = () => get<any[]>('/dict/type/list')
export const dictData = (dictType: string) => get<any[]>(`/dict/data/${dictType}`)
export const saveDictType = (payload: Record<string, unknown>) => post('/dict/type', payload)
export const saveDictData = (payload: Record<string, unknown>) => post('/dict/data', payload)
export const deleteDictType = (id: number | string) => del(`/dict/type/${id}`)
export const deleteDictData = (id: number | string) => del(`/dict/data/${id}`)
export const configList = () => get<any[]>('/config/list')
export const saveConfig = (payload: Record<string, unknown>) => post('/config', payload)
export const deleteConfig = (id: number) => del(`/config/${id}`)
